# DO NOT EDIT THIS FILE Make yours changes in /utils/docker-bake.blueprint.hcl

group "default" {
   targets = [
     
     "php84",
     "php83",
     "php82",
     "php81",
   ]
}

group "php84-apache-all" {
   targets = [
     "php84-slim-apache",
     "php84-apache",
     "php84-apache-node22","php84-apache-node20","php84-apache-node18",
   ]
}
group "php84-fpm-all" {
   targets = [
     "php84-slim-fpm",
     "php84-fpm",
     "php84-fpm-node22","php84-fpm-node20","php84-fpm-node18",
   ]
}
group "php84-cli-all" {
   targets = [
     "php84-slim-cli",
     "php84-cli",
     "php84-cli-node22","php84-cli-node20","php84-cli-node18",
   ]
}
group "php83-apache-all" {
   targets = [
     "php83-slim-apache",
     "php83-apache",
     "php83-apache-node22","php83-apache-node20","php83-apache-node18",
   ]
}
group "php83-fpm-all" {
   targets = [
     "php83-slim-fpm",
     "php83-fpm",
     "php83-fpm-node22","php83-fpm-node20","php83-fpm-node18",
   ]
}
group "php83-cli-all" {
   targets = [
     "php83-slim-cli",
     "php83-cli",
     "php83-cli-node22","php83-cli-node20","php83-cli-node18",
   ]
}
group "php82-apache-all" {
   targets = [
     "php82-slim-apache",
     "php82-apache",
     "php82-apache-node22","php82-apache-node20","php82-apache-node18",
   ]
}
group "php82-fpm-all" {
   targets = [
     "php82-slim-fpm",
     "php82-fpm",
     "php82-fpm-node22","php82-fpm-node20","php82-fpm-node18",
   ]
}
group "php82-cli-all" {
   targets = [
     "php82-slim-cli",
     "php82-cli",
     "php82-cli-node22","php82-cli-node20","php82-cli-node18",
   ]
}
group "php81-apache-all" {
   targets = [
     "php81-slim-apache",
     "php81-apache",
     "php81-apache-node22","php81-apache-node20","php81-apache-node18",
   ]
}
group "php81-fpm-all" {
   targets = [
     "php81-slim-fpm",
     "php81-fpm",
     "php81-fpm-node22","php81-fpm-node20","php81-fpm-node18",
   ]
}
group "php81-cli-all" {
   targets = [
     "php81-slim-cli",
     "php81-cli",
     "php81-cli-node22","php81-cli-node20","php81-cli-node18",
   ]
}


group "php84" {
   targets = ["php84-apache-all","php84-fpm-all","php84-cli-all",]
}
group "php83" {
   targets = ["php83-apache-all","php83-fpm-all","php83-cli-all",]
}
group "php82" {
   targets = ["php82-apache-all","php82-fpm-all","php82-cli-all",]
}
group "php81" {
   targets = ["php81-apache-all","php81-fpm-all","php81-cli-all",]
}

variable "REPO" {default = "thecodingmachine/php"}
variable "TAG_PREFIX" {default = ""}
variable "PHP_PATCH_MINOR" {default = ""}
variable "IS_RELEASE" {default = "0"}
variable "GLOBAL_VERSION" {default = "v5"}

function "tag" {
    params = [PHP_VERSION, VARIANT]
    result = [
      equal("1",IS_RELEASE) ? "${REPO}:${PHP_VERSION}-${GLOBAL_VERSION}-${VARIANT}" : "",
      equal("1",IS_RELEASE) ? (notequal("",PHP_PATCH_MINOR) ? "${REPO}:${PHP_PATCH_MINOR}-${GLOBAL_VERSION}-${VARIANT}": "") : "",
      "${REPO}:${TAG_PREFIX}${PHP_VERSION}-${GLOBAL_VERSION}-${VARIANT}",
    ]
}

target "default" {
  context = "."
  args = {
    GLOBAL_VERSION = "${GLOBAL_VERSION}"
  }
  #platforms = ["linux/amd64", "linux/arm64"]
  platforms = [BAKE_LOCAL_PLATFORM]
  pull = true
  output = ["type=docker"] # export in local docker
}


###########################
##    PHP 8.4
###########################
# thecodingmachine/php:8.4-v5-slim-apache
target "php84-slim-apache" {
  inherits = ["default"]
  tags = tag("8.4", "slim-apache")
  dockerfile = "Dockerfile.slim.apache"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "apache"
  }
}

# thecodingmachine/php:8.4-v5-apache
target "php84-apache" {
  inherits = ["default"]
  tags = tag("8.4", "apache")
  dockerfile = "Dockerfile.apache"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "apache"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php84-slim-apache"
  }
}

# thecodingmachine/php:8.4-v5-apache-node22
target "php84-apache-node22" {
  inherits = ["default"]
  tags = tag("8.4", "apache-node22")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "apache-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php84-apache"
  }
}

# thecodingmachine/php:8.4-v5-apache-node20
target "php84-apache-node20" {
  inherits = ["default"]
  tags = tag("8.4", "apache-node20")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "apache-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php84-apache"
  }
}

# thecodingmachine/php:8.4-v5-apache-node18
target "php84-apache-node18" {
  inherits = ["default"]
  tags = tag("8.4", "apache-node18")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "apache-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php84-apache"
  }
}

###########################
##    PHP 8.4
###########################
# thecodingmachine/php:8.4-v5-slim-fpm
target "php84-slim-fpm" {
  inherits = ["default"]
  tags = tag("8.4", "slim-fpm")
  dockerfile = "Dockerfile.slim.fpm"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "fpm"
  }
}

# thecodingmachine/php:8.4-v5-fpm
target "php84-fpm" {
  inherits = ["default"]
  tags = tag("8.4", "fpm")
  dockerfile = "Dockerfile.fpm"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "fpm"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php84-slim-fpm"
  }
}

# thecodingmachine/php:8.4-v5-fpm-node22
target "php84-fpm-node22" {
  inherits = ["default"]
  tags = tag("8.4", "fpm-node22")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "fpm-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php84-fpm"
  }
}

# thecodingmachine/php:8.4-v5-fpm-node20
target "php84-fpm-node20" {
  inherits = ["default"]
  tags = tag("8.4", "fpm-node20")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "fpm-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php84-fpm"
  }
}

# thecodingmachine/php:8.4-v5-fpm-node18
target "php84-fpm-node18" {
  inherits = ["default"]
  tags = tag("8.4", "fpm-node18")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "fpm-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php84-fpm"
  }
}

###########################
##    PHP 8.4
###########################
# thecodingmachine/php:8.4-v5-slim-cli
target "php84-slim-cli" {
  inherits = ["default"]
  tags = tag("8.4", "slim-cli")
  dockerfile = "Dockerfile.slim.cli"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "cli"
  }
}

# thecodingmachine/php:8.4-v5-cli
target "php84-cli" {
  inherits = ["default"]
  tags = tag("8.4", "cli")
  dockerfile = "Dockerfile.cli"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "cli"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php84-slim-cli"
  }
}

# thecodingmachine/php:8.4-v5-cli-node22
target "php84-cli-node22" {
  inherits = ["default"]
  tags = tag("8.4", "cli-node22")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "cli-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php84-cli"
  }
}

# thecodingmachine/php:8.4-v5-cli-node20
target "php84-cli-node20" {
  inherits = ["default"]
  tags = tag("8.4", "cli-node20")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "cli-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php84-cli"
  }
}

# thecodingmachine/php:8.4-v5-cli-node18
target "php84-cli-node18" {
  inherits = ["default"]
  tags = tag("8.4", "cli-node18")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.4"
    VARIANT = "cli-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php84-cli"
  }
}

###########################
##    PHP 8.3
###########################
# thecodingmachine/php:8.3-v5-slim-apache
target "php83-slim-apache" {
  inherits = ["default"]
  tags = tag("8.3", "slim-apache")
  dockerfile = "Dockerfile.slim.apache"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "apache"
  }
}

# thecodingmachine/php:8.3-v5-apache
target "php83-apache" {
  inherits = ["default"]
  tags = tag("8.3", "apache")
  dockerfile = "Dockerfile.apache"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "apache"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php83-slim-apache"
  }
}

# thecodingmachine/php:8.3-v5-apache-node22
target "php83-apache-node22" {
  inherits = ["default"]
  tags = tag("8.3", "apache-node22")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "apache-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php83-apache"
  }
}

# thecodingmachine/php:8.3-v5-apache-node20
target "php83-apache-node20" {
  inherits = ["default"]
  tags = tag("8.3", "apache-node20")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "apache-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php83-apache"
  }
}

# thecodingmachine/php:8.3-v5-apache-node18
target "php83-apache-node18" {
  inherits = ["default"]
  tags = tag("8.3", "apache-node18")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "apache-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php83-apache"
  }
}

###########################
##    PHP 8.3
###########################
# thecodingmachine/php:8.3-v5-slim-fpm
target "php83-slim-fpm" {
  inherits = ["default"]
  tags = tag("8.3", "slim-fpm")
  dockerfile = "Dockerfile.slim.fpm"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "fpm"
  }
}

# thecodingmachine/php:8.3-v5-fpm
target "php83-fpm" {
  inherits = ["default"]
  tags = tag("8.3", "fpm")
  dockerfile = "Dockerfile.fpm"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "fpm"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php83-slim-fpm"
  }
}

# thecodingmachine/php:8.3-v5-fpm-node22
target "php83-fpm-node22" {
  inherits = ["default"]
  tags = tag("8.3", "fpm-node22")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "fpm-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php83-fpm"
  }
}

# thecodingmachine/php:8.3-v5-fpm-node20
target "php83-fpm-node20" {
  inherits = ["default"]
  tags = tag("8.3", "fpm-node20")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "fpm-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php83-fpm"
  }
}

# thecodingmachine/php:8.3-v5-fpm-node18
target "php83-fpm-node18" {
  inherits = ["default"]
  tags = tag("8.3", "fpm-node18")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "fpm-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php83-fpm"
  }
}

###########################
##    PHP 8.3
###########################
# thecodingmachine/php:8.3-v5-slim-cli
target "php83-slim-cli" {
  inherits = ["default"]
  tags = tag("8.3", "slim-cli")
  dockerfile = "Dockerfile.slim.cli"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "cli"
  }
}

# thecodingmachine/php:8.3-v5-cli
target "php83-cli" {
  inherits = ["default"]
  tags = tag("8.3", "cli")
  dockerfile = "Dockerfile.cli"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "cli"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php83-slim-cli"
  }
}

# thecodingmachine/php:8.3-v5-cli-node22
target "php83-cli-node22" {
  inherits = ["default"]
  tags = tag("8.3", "cli-node22")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "cli-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php83-cli"
  }
}

# thecodingmachine/php:8.3-v5-cli-node20
target "php83-cli-node20" {
  inherits = ["default"]
  tags = tag("8.3", "cli-node20")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "cli-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php83-cli"
  }
}

# thecodingmachine/php:8.3-v5-cli-node18
target "php83-cli-node18" {
  inherits = ["default"]
  tags = tag("8.3", "cli-node18")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.3"
    VARIANT = "cli-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php83-cli"
  }
}

###########################
##    PHP 8.2
###########################
# thecodingmachine/php:8.2-v5-slim-apache
target "php82-slim-apache" {
  inherits = ["default"]
  tags = tag("8.2", "slim-apache")
  dockerfile = "Dockerfile.slim.apache"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "apache"
  }
}

# thecodingmachine/php:8.2-v5-apache
target "php82-apache" {
  inherits = ["default"]
  tags = tag("8.2", "apache")
  dockerfile = "Dockerfile.apache"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "apache"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php82-slim-apache"
  }
}

# thecodingmachine/php:8.2-v5-apache-node22
target "php82-apache-node22" {
  inherits = ["default"]
  tags = tag("8.2", "apache-node22")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "apache-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php82-apache"
  }
}

# thecodingmachine/php:8.2-v5-apache-node20
target "php82-apache-node20" {
  inherits = ["default"]
  tags = tag("8.2", "apache-node20")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "apache-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php82-apache"
  }
}

# thecodingmachine/php:8.2-v5-apache-node18
target "php82-apache-node18" {
  inherits = ["default"]
  tags = tag("8.2", "apache-node18")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "apache-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php82-apache"
  }
}

###########################
##    PHP 8.2
###########################
# thecodingmachine/php:8.2-v5-slim-fpm
target "php82-slim-fpm" {
  inherits = ["default"]
  tags = tag("8.2", "slim-fpm")
  dockerfile = "Dockerfile.slim.fpm"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "fpm"
  }
}

# thecodingmachine/php:8.2-v5-fpm
target "php82-fpm" {
  inherits = ["default"]
  tags = tag("8.2", "fpm")
  dockerfile = "Dockerfile.fpm"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "fpm"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php82-slim-fpm"
  }
}

# thecodingmachine/php:8.2-v5-fpm-node22
target "php82-fpm-node22" {
  inherits = ["default"]
  tags = tag("8.2", "fpm-node22")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "fpm-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php82-fpm"
  }
}

# thecodingmachine/php:8.2-v5-fpm-node20
target "php82-fpm-node20" {
  inherits = ["default"]
  tags = tag("8.2", "fpm-node20")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "fpm-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php82-fpm"
  }
}

# thecodingmachine/php:8.2-v5-fpm-node18
target "php82-fpm-node18" {
  inherits = ["default"]
  tags = tag("8.2", "fpm-node18")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "fpm-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php82-fpm"
  }
}

###########################
##    PHP 8.2
###########################
# thecodingmachine/php:8.2-v5-slim-cli
target "php82-slim-cli" {
  inherits = ["default"]
  tags = tag("8.2", "slim-cli")
  dockerfile = "Dockerfile.slim.cli"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "cli"
  }
}

# thecodingmachine/php:8.2-v5-cli
target "php82-cli" {
  inherits = ["default"]
  tags = tag("8.2", "cli")
  dockerfile = "Dockerfile.cli"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "cli"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php82-slim-cli"
  }
}

# thecodingmachine/php:8.2-v5-cli-node22
target "php82-cli-node22" {
  inherits = ["default"]
  tags = tag("8.2", "cli-node22")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "cli-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php82-cli"
  }
}

# thecodingmachine/php:8.2-v5-cli-node20
target "php82-cli-node20" {
  inherits = ["default"]
  tags = tag("8.2", "cli-node20")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "cli-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php82-cli"
  }
}

# thecodingmachine/php:8.2-v5-cli-node18
target "php82-cli-node18" {
  inherits = ["default"]
  tags = tag("8.2", "cli-node18")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.2"
    VARIANT = "cli-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php82-cli"
  }
}

###########################
##    PHP 8.1
###########################
# thecodingmachine/php:8.1-v5-slim-apache
target "php81-slim-apache" {
  inherits = ["default"]
  tags = tag("8.1", "slim-apache")
  dockerfile = "Dockerfile.slim.apache"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "apache"
  }
}

# thecodingmachine/php:8.1-v5-apache
target "php81-apache" {
  inherits = ["default"]
  tags = tag("8.1", "apache")
  dockerfile = "Dockerfile.apache"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "apache"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php81-slim-apache"
  }
}

# thecodingmachine/php:8.1-v5-apache-node22
target "php81-apache-node22" {
  inherits = ["default"]
  tags = tag("8.1", "apache-node22")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "apache-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php81-apache"
  }
}

# thecodingmachine/php:8.1-v5-apache-node20
target "php81-apache-node20" {
  inherits = ["default"]
  tags = tag("8.1", "apache-node20")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "apache-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php81-apache"
  }
}

# thecodingmachine/php:8.1-v5-apache-node18
target "php81-apache-node18" {
  inherits = ["default"]
  tags = tag("8.1", "apache-node18")
  dockerfile = "Dockerfile.apache.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "apache-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php81-apache"
  }
}

###########################
##    PHP 8.1
###########################
# thecodingmachine/php:8.1-v5-slim-fpm
target "php81-slim-fpm" {
  inherits = ["default"]
  tags = tag("8.1", "slim-fpm")
  dockerfile = "Dockerfile.slim.fpm"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "fpm"
  }
}

# thecodingmachine/php:8.1-v5-fpm
target "php81-fpm" {
  inherits = ["default"]
  tags = tag("8.1", "fpm")
  dockerfile = "Dockerfile.fpm"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "fpm"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php81-slim-fpm"
  }
}

# thecodingmachine/php:8.1-v5-fpm-node22
target "php81-fpm-node22" {
  inherits = ["default"]
  tags = tag("8.1", "fpm-node22")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "fpm-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php81-fpm"
  }
}

# thecodingmachine/php:8.1-v5-fpm-node20
target "php81-fpm-node20" {
  inherits = ["default"]
  tags = tag("8.1", "fpm-node20")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "fpm-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php81-fpm"
  }
}

# thecodingmachine/php:8.1-v5-fpm-node18
target "php81-fpm-node18" {
  inherits = ["default"]
  tags = tag("8.1", "fpm-node18")
  dockerfile = "Dockerfile.fpm.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "fpm-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php81-fpm"
  }
}

###########################
##    PHP 8.1
###########################
# thecodingmachine/php:8.1-v5-slim-cli
target "php81-slim-cli" {
  inherits = ["default"]
  tags = tag("8.1", "slim-cli")
  dockerfile = "Dockerfile.slim.cli"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "cli"
  }
}

# thecodingmachine/php:8.1-v5-cli
target "php81-cli" {
  inherits = ["default"]
  tags = tag("8.1", "cli")
  dockerfile = "Dockerfile.cli"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "cli"
    FROM_IMAGE = "slim"
  }
  contexts = {
    slim = "target:php81-slim-cli"
  }
}

# thecodingmachine/php:8.1-v5-cli-node22
target "php81-cli-node22" {
  inherits = ["default"]
  tags = tag("8.1", "cli-node22")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "cli-node22"
    FROM_IMAGE = "fat"
    NODE_VERSION = "22"
  }
  contexts = {
    fat = "target:php81-cli"
  }
}

# thecodingmachine/php:8.1-v5-cli-node20
target "php81-cli-node20" {
  inherits = ["default"]
  tags = tag("8.1", "cli-node20")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "cli-node20"
    FROM_IMAGE = "fat"
    NODE_VERSION = "20"
  }
  contexts = {
    fat = "target:php81-cli"
  }
}

# thecodingmachine/php:8.1-v5-cli-node18
target "php81-cli-node18" {
  inherits = ["default"]
  tags = tag("8.1", "cli-node18")
  dockerfile = "Dockerfile.cli.node"
  args = {
    PHP_VERSION = "8.1"
    VARIANT = "cli-node18"
    FROM_IMAGE = "fat"
    NODE_VERSION = "18"
  }
  contexts = {
    fat = "target:php81-cli"
  }
}


